### PR TITLE
Rerender

### PR DESCRIPTION
**Pull request by kmuehlbauer**

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
Running into issues with matplotlib _macosx backend, while importing `wradlib` on osx:

https://travis-ci.org/conda-forge/wradlib-feedstock/jobs/186272029#L749

Tried the `pythonw` approach in https://github.com/conda-forge/matplotlib-feedstock/pull/87 to no avail:

https://travis-ci.org/conda-forge/wradlib-feedstock/jobs/186275593#L734

Any hints @conda-forge/matplotlib?

**Comment by kmuehlbauer** [comment]
@ocefpaf Maybe you have an idea, how to fix this maxosx issue?

**Comment by ocefpaf** [comment]
@kmuehlbauer I don't know the first thing about Mac. Sorry. Maybe @dopplershift can help you here.

**Comment by kmuehlbauer** [comment]
OK, let's wait for those with more mac expertise than us ;-).

**Comment by tacaswell** [comment]
One possible way around this would be to create a `~/.config/matplotlib/matplotlibrc` file with

```
backend : Agg
```

to force a non-interactive backend for building + tests.

**Comment by kmuehlbauer** [comment]
@tacaswell Is this also possible to do in the import section? Like this maybe:

```python
import matplotlib
matplotlib.use('Agg')
import wradlib
```

**Comment by tacaswell** [comment]
@kmuehlbauer Yes (as you have already proven) ;)

**Comment by kmuehlbauer** [comment]
@tacaswell Yes, that did the trick. Thanks for the hint!

**Pull request merged**
