### PR TITLE
rerender

### PR DESCRIPTION
**Pull request by ocefpaf**
First step to fix the failure we are seeing on [master](https://travis-ci.org/conda-forge/wradlib-feedstock/jobs/127740753).

### CODE REVIEW

**Comment by ocefpaf** [comment]
I suspect that `matplotlib` might be the culprit of the `libpng` downgrade here.

xref: https://github.com/conda-forge/matplotlib-feedstock/pull/15

**Comment by kmuehlbauer** [comment]
@ocefpaf Can we merge this anyway?

**Comment by ocefpaf** [comment]
If that helps you we can, but let's try to get https://github.com/conda-forge/matplotlib-feedstock/pull/15 in first.

**Comment by ocefpaf** [comment]
@kmuehlbauer I narrowed it down to the default channel `freetype` for  OS X. That package requires libpng and it seems to be pinned to the old version.

**Comment by kmuehlbauer** [comment]
@ocefpaf crazy stuff, if we have `matplotlib` as build-dependency than also freetype is included which pins libpng. OK, let's merge this here. I'll then remove scipy, matplotlib, h5py, netcdf4 and gdal from the build-dependencies. For installing via `python setup.py install` only `python` and `numpy` is needed.

**Comment by ocefpaf** [comment]
Give me 3-4 hours and I will merge this. I am preparing a `freetype` package. Hold on...

**Comment by ocefpaf** [comment]
@kmuehlbauer we have freetype now, but to change the pinning properly we need to build it for Windows. (We are almost there. See https://github.com/conda-forge/freetype-feedstock/pull/3)

**Comment by kmuehlbauer** [comment]
@ocefpaf Great Work! Green lights in https://github.com/conda-forge/freetype-feedstock/pull/3!

**Comment by ocefpaf** [comment]
@kmuehlbauer AppVeyor is green, but the Windows version is useless right now :unamused: 

I don't really want to pin Windows and *nix differently, but if I don't solve the Windows build soon I will do that as `wradlib` stuck until then.

**Comment by ocefpaf** [comment]
Ping @kmuehlbauer. We have green!

**Pull request merged**
