### PR TITLE
Update feedstock

### LINKED ISSUE #8: OSX: conda-forge libpng is not selected
Having gdal as dependency, the correct libpng from conda-forge channel isn't picked up.

@ocefpaf, @jjhelmus Is this the with the `conda-build 1.20.1` glitch? How do I re-render the feedstock and incorporate those workaround-changes? Didn't do that before.

### PR DESCRIPTION
**Pull request by ocefpaf**
@kmuehlbauer this `feedstock` was quite old and due for a re-rendering and some updates. Hopefully this will fix #8 too.

### CODE REVIEW

**Comment by ocefpaf** [comment]
I also notice that we need to pin `scipy` until https://github.com/wradlib/wradlib/commit/3dd57a195dcdb562672d058ce51b0ec6fa2961b8 makes into the next release.

**Comment by ocefpaf** [comment]
The problem is that `openblas` again. There was an update in the library to multo-threaded and the previous versions was not re-built nor pinned. (If I had a penny for every problem `openblas` added to conda-forge I would be rich now.)

I won't try to talk with the `openblas` maintainers again as it is not worth it. One alternative is to make the `0.9.0` release of to patch so we can use `scipy 0.18`

```
import: 'wradlib'
Traceback (most recent call last):
  File "/Users/travis/miniconda3/conda-bld/test-tmp_dir/run_test.py", line 26, in <module>
    import wradlib
  File "/Users/travis/miniconda3/envs/_test/lib/python2.7/site-packages/wradlib/__init__.py", line 28, in <module>
    from . import adjust
  File "/Users/travis/miniconda3/envs/_test/lib/python2.7/site-packages/wradlib/adjust.py", line 109, in <module>
    from scipy.spatial import cKDTree
  File "/Users/travis/miniconda3/envs/_test/lib/python2.7/site-packages/scipy/spatial/__init__.py", line 93, in <module>
    from .qhull import *
ImportError: dlopen(/Users/travis/miniconda3/envs/_test/lib/python2.7/site-packages/scipy/spatial/qhull.so, 2): Library not loaded: @rpath/libopenblas-r0.2.18.dylib
  Referenced from: /Users/travis/miniconda3/envs/_test/lib/python2.7/site-packages/scipy/spatial/qhull.so
  Reason: image not found
TESTS FAILED: wradlib-0.8.0-py27_2
```

**Comment by ocefpaf** [comment]
It is weird that the patches are failing. It seems that the original code has different line endings. So out only option is to way for the `0.9.0`.

**Comment by kmuehlbauer** [comment]
Sorry, @ocefpaf, I didn't manage to get 0.9.0 ready. I'll finalize 0.9.0 when  I'm back in two weeks. So don't waste your time on this one. Hopefully the openblas stuff is fixed then.

**Comment by ocefpaf** [comment]
> Sorry, @ocefpaf, I didn't manage to get 0.9.0 ready. I'll finalize 0.9.0 when  I'm back in two weeks.

No problem.

> So don't waste your time on this one.

You can still merge this to update the `feedstock` and get Linux and Windows back into shape.

> Hopefully the openblas stuff is fixed then. 

Probably not, but I believe that won't affect `scipy 0.18.0`.

**Comment by jakirkham** [comment]
If building `scipy` version `0.17.x` with the new `openblas` will help, I'd be happy to try that.

**Comment by jakirkham** [comment]
It's because we rebuilt `openblas` to support multithreading in PR ( https://github.com/conda-forge/openblas-feedstock/pull/9 ). However, this resulted in an ABI break. We went and rebuilt everything. However, as we were only supporting `scipy` version `0.18.0` at the time (latest), we did not rebuild older `scipy`s like version `0.17.1`. As it seems this older `scipy` version is needed here, we can rebuild `0.17.1`, as PR ( https://github.com/conda-forge/scipy-feedstock/pull/9 ) will do, to fix this issue.

**Comment by kmuehlbauer** [comment]
@jakirkham @ocefpaf We can proceed now with fixing this.

Unfortunately wradlib v 0.9.0 is still due, so getting 0.8.0 working again is better than waiting :grimacing:

**Comment by jakirkham** [comment]
Sounds reasonable to me. If we can get someone to merge those PRs, we should be good to go on this in ~1hr.

**Comment by kmuehlbauer** [comment]
I'll have a look then and restart the CI's here.

**Comment by jakirkham** [comment]
So those have been built and uploaded. Looks like the CIs have been restarted and are working thus far. Please let me know if you run into other issues.

**Comment by kmuehlbauer** [comment]
I already restarted travis. Builds for python 3.4 and 3.5 are finished now. python 2.7 didn't start yet.

**Comment by jakirkham** [comment]
Looks like the Travis CI OS X workers are saturated ATM. ( https://www.traviscistatus.com/ ) So we might be dealing with long wait times. It is possible Travis CI is having some issues of their own too. Will keep you apprised of any new developments.

**Comment by jakirkham** [comment]
It appears this is now passing. 😄

**Pull request merged**
