### PR TITLE
V0.11.2

### PR DESCRIPTION
**Pull request by kmuehlbauer**

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
Weird error on CircleCI while Travis (on my instance) and Appveyor are happy.

@ocefpaf  Have you seen anything like that before? Ping also @jakirkham.
```
Traceback (most recent call last):
  File "/feedstock_root/build_artefacts/wradlib_1513604644085/test_tmp/run_test.py", line 2, in <module>
    import wradlib
  File "/feedstock_root/build_artefacts/wradlib_1513604644085/_t_env/lib/python2.7/site-packages/wradlib/__init__.py", line 43, in <module>
    from . import verify  # noqa
  File "/feedstock_root/build_artefacts/wradlib_1513604644085/_t_env/lib/python2.7/site-packages/wradlib/verify.py", line 24, in <module>
    import: 'wradlib'
import matplotlib.pyplot as pl
  File "/feedstock_root/build_artefacts/wradlib_1513604644085/_t_env/lib/python2.7/site-packages/matplotlib/pyplot.py", line 32, in <module>
    import matplotlib.colorbar
  File "/feedstock_root/build_artefacts/wradlib_1513604644085/_t_env/lib/python2.7/site-packages/matplotlib/colorbar.py", line 36, in <module>
    import matplotlib.contour as contour
  File "/feedstock_root/build_artefacts/wradlib_1513604644085/_t_env/lib/python2.7/site-packages/matplotlib/contour.py", line 15, in <module>
    import matplotlib._contour as _contour
ImportError: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /feedstock_root/build_artefacts/wradlib_1513604644085/_t_env/lib/python2.7/site-packages/matplotlib/_contour.so)
TESTS FAILED: wradlib-0.11.2-py27_0.tar.bz2
```

**Comment by ocefpaf** [comment]
Our packages are starting the pull in `defaults` compilers so we need to start factoring that in our builds.
This is the lat `matplotlib` linkages report:

```
freetype-2.8.1-0:
    libfreetype.so.6 (lib/libfreetype.so.6)

libgcc-ng-7.2.0-h7cc24e2_2:
    libgcc_s.so.1 (lib/libgcc_s.so.1)

libpng-1.6.34-0:
    libpng16.so.16 (lib/libpng16.so.16)

libstdcxx-ng-7.2.0-h7a57d05_2:
    libstdc++.so.6 (lib/libstdc++.so.6)

zlib-1.2.11-0:
    libz.so.1 (lib/libz.so.1)

system:
    libc.so.6 (/lib64/libc.so.6)
    libm.so.6 (/lib64/libm.so.6)
    libpthread.so.0 (/lib64/libpthread.so.0)
    linux-vdso.so.1 ()
```

A workaround would be adding `libgcc-ng` here, but we need a better solution soon.

**Comment by kmuehlbauer** [comment]
@ocefpaf Means that `matplotlib` is currently broken? Should I open an issue there?

**Comment by kmuehlbauer** [comment]
Just for my reference: https://github.com/conda-forge/matplotlib-feedstock/issues/32

**Comment by ocefpaf** [comment]
> @ocefpaf Means that `matplotlib` is currently broken? Should I open an issue there?

That is one way of putting it, yes :smile:

**Comment by jakirkham** [comment]
@conda-forge-admin, please rerender.

**Comment by kmuehlbauer** [comment]
For latest matplotlib 
`matplotlib                2.1.1                    py27_1    conda-forge` 
I get these linkages reported. Something is terribly broken inside the CircleCI build setup.

```
freetype-2.8.1-0:
    libfreetype.so.6 (lib/libfreetype.so.6)

libpng-1.6.34-0:
    libpng16.so.16 (lib/libpng16.so.16)

python-2.7.14-3:
    libpython2.7.so.1.0 (lib/libpython2.7.so.1.0)

zlib-1.2.11-0:
    libz.so.1 (lib/libz.so.1)

system:
    libc.so.6 (/lib64/libc.so.6)
    libdl.so.2 (/lib64/libdl.so.2)
    libgcc_s.so.1 (/lib64/libgcc_s.so.1)
    libm.so.6 (/lib64/libm.so.6)
    libpthread.so.0 (/lib64/libpthread.so.0)
    libstdc++.so.6 (/usr/lib64/libstdc++.so.6)
    libutil.so.1 (/lib64/libutil.so.1)

```

**Comment by jakirkham** [comment]
I have a theory that I'd like to partially test here by re-rendering the feedstock. If I'm right, only `python` 2.7 and 3.5 will fail on Linux.

**Comment by kmuehlbauer** [comment]
@jakirkham OK, I assume the rerender will split the Circle build into three separate builds.

**Comment by jakirkham** [comment]
Correct.

Also the other part of my theory seems to be correct thus far. Namely the `python` 2.7 and 3.5 builds were built in the presence of a newer `libgcc` due to dependency issues. A rebuild of `matplotlib` should resolve this issue. ( https://github.com/conda-forge/matplotlib-feedstock/pull/137 )

**Comment by jakirkham** [comment]
Linking the failed builds for [Python 2.7]( https://circleci.com/gh/conda-forge/wradlib-feedstock/60 ) and [Python 3.5]( https://circleci.com/gh/conda-forge/wradlib-feedstock/62 ) and the passing [Python 3.6 build]( https://circleci.com/gh/conda-forge/wradlib-feedstock/61 ) for history.

**Comment by jakirkham** [comment]
Toggling for CIs.

**Comment by jakirkham** [comment]
Alright retriggered the CI builds now that `matplotlib` has been rebuilt. Let's see how it goes.

**Comment by jakirkham** [comment]
Looks like the CircleCI builds are passing now. :)

**Pull request merged**
