### PR TITLE
Re-render with conda-smithy 0.10.4

### PR DESCRIPTION
**Pull request by jakirkham**
Closes https://github.com/conda-forge/wradlib-feedstock/pull/11
Closes https://github.com/conda-forge/wradlib-feedstock/pull/12

Simply re-renders with `conda-smithy` 0.10.4. Normally we would have used the automatically generated re-rendering PR. However, it failed to properly move to a recent commit. So, we have regenerated this by hand instead.

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
I somehow lost track in all these PR's. For this one here, it seems, that there is some dependency issue with `gdal`. But there is no clue in the log, why this is happening.

```
Error: The following specifications were found to be in conflict:
  - gdal -> jpeg 9*
  - gdal -> numpy 1.8*|1.9*
  - gdal -> python 2.6*|2.7*|3.3*|3.4*
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package. 
```

**Comment by jakirkham** [comment]
I think once we get a pinning PR this is going to make more sense or, if we are lucky, just go away altogether. Who knows what the solver is optimizing for here.

**Comment by kmuehlbauer** [comment]
The dependencies here are not listed in the pinning wiki:

```
- python
- numpy 
- scipy 
- matplotlib 
- h5py 
- netcdf4 
- gdal
```

Although some of them have dependencies listed there (as of now):

matplotlib:
- freetype 2.6               # should be 'freetype 2.6*'
- libpng 1.6\*                 # 'libpng >=1.6.21,<1.7'

h5py:
- hdf 1.8.17*

netcdf4:
- hdf5 1.8.17|1.8.17.\*     # should be 'hdf5 1.8.17*'
- libnetcdf 4.4.*

gdal:
- hdf5 1.8.17*
- libnetcdf 4.4*
- libtiff 4.0.6                 # should be 'libtiff 4.0.*'
- libpng 1.6\*                # should be 'libpng >=1.6.21,<1.7'
- jpeg 9*

I'm totally out of ideas, how to correctly file an pinning PR with these second order dependencies.

**Comment by jakirkham** [comment]
> hdf5 1.8.17|1.8.17.\* # should be 'hdf5 1.8.17*'

Actually, no. This was intentional. This forces it to either be `1.8.17` or `1.8.17.x`. The reason is HDF5 may only have 3 version numbers, but can optionally have a 4th. This is a bit more accurate than `1.8.17*` as it could allow `1.8.170` not saying that will happen (it's pretty unlikely), but still it is easy to block that possibility so we do. In any event, these won't be in conflict as they will still get some `1.8.17` version.

**Comment by jakirkham** [comment]
See issue ( https://github.com/conda-forge/gdal-feedstock/issues/70 ) for fixing `gdal`'s pinnings.

**Comment by jakirkham** [comment]
Matplotlib will be fixed once this PR ( https://github.com/conda-forge/matplotlib-feedstock/pull/29 ) is merged.

**Comment by jakirkham** [comment]
Let's see if the pinning issues in these dependencies can be resolved.

**Comment by jakirkham** [comment]
Looks like this is a simple problem, @kmuehlbauer. Not all of the `gdal` packages were built on Windows. ( https://github.com/conda-forge/gdal-feedstock/issues/71 ). I have restarted the CI there. Hopefully it will be done building the missing packages on Windows by the time you are up. 😉 Feel free to give this a restart then. Please let me know if you run into more issues then.

**Comment by jakirkham** [comment]
Actually went ahead and restarted this as it is later in the queue. Hopefully everything goes smoothly.

**Comment by jakirkham** [comment]
I should add the previous build of gdal (version 2.1.0 build number 3) would have introduced a number of pinning conflicts including HDF5 and libnetcdf. However, build number 4 resolves these.

**Comment by jakirkham** [comment]
Weird. It's still failing. Maybe we need some pinning updates as well.

**Comment by kmuehlbauer** [comment]
@jakirkham 

> Actually, no. This was intentional.

Can you have a look at the pinning wiki. It would need an update then. I just compared to the wiki.

**Comment by kmuehlbauer** [comment]
@jakirkham 

`matplotlib` is blocking this, because `matplotlib` itself depends on `qt-4.8.7` which depends on 
`jpeg 8`.

See https://github.com/conda-forge/matplotlib-feedstock/pull/29#issuecomment-224184366 ff.

**Comment by jakirkham** [comment]
So, the pinning wiki is a bit out-of-date. We can update it for sure. Though we have been discussing removing it as the source of pinnings has moved to join the code that generates pinning PRs. This is where one should now look for the [pinnings](https://github.com/conda-forge/conda-forge.github.io/blob/1ec23e63ddacf222c89ece004d8d74c21557dbd4/scripts/pin_the_slow_way.py#L32-L48).

**Comment by jakirkham** [comment]
Yeah, it makes sense that `qt` would be the cause of our woes here, but the conflict that we are given is pretty unclear. It would be nice if it explained the `matplotlib` side of the conflict. FWICT it was initially just a matter of `gdal` not exisiting. Though maybe this is pointing out that `jpeg` wasn't pinned in old copies of `gdal`.

**Comment by kmuehlbauer** [comment]
@jakirkham

I tested this on my windows box. I added the dependencies one by one, if there where no conflict. matplotlib, qt  and pyqt where the only leftovers. And all complained about downgrading jpeg to 8d. 

And the dep-chain there is matplotlib depends on pyqt and pyqt on qt. 

So, gdal is only mentioned because it is itself pinned to `jpeg 9`, if you install this as a batch.

**Comment by jakirkham** [comment]
@ocefpaf @pelson, do you have any thoughts about this? Basically `gdal` and `matplotlib` cannot exist in the same environment. This is making it hard to install `wradlib`. In particular, as `matplotlib` requires `pyqt`, which requires `qt`, we find ourselves with a conflict over the `jpeg` version. Could we downgrade `jpeg` throughout the stack. What problems might that cause? Unfortunately packaging `qt` might not be an option for the near future due to build time.

**Comment by ocefpaf** [comment]
This is a known problem and @gillins and @msarahan is on it. The Qt recipes are brewing, we are just waiting on a way to run them :smile:

**Comment by jakirkham** [comment]
Would it be alright if we merge the re-rendering anyways, @kmuehlbauer? I know this is failing, but I think it is helpful to see that so we are reminded of this problem and try to fix it once we can.

Also, I would like us to all be on the same infrastructure, but this is on old infrastructure (e.g. the docker image). Merging this would put the wradlib feedstock on the same footing as everything else.

**Comment by kmuehlbauer** [comment]
@jakirkham Sure, go ahead.

**Comment by jakirkham** [comment]
Thanks @kmuehlbauer.

**Pull request merged**
