### PR TITLE
Rerender

### PR DESCRIPTION
**Pull request by kmuehlbauer**

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@conda-forge-admin, please rerender

**Comment by kmuehlbauer** [comment]
@ocefpaf Just to be sure, what do I have to do to enable python3.7 and update to the latest pinnings?

**Comment by ocefpaf** [comment]
> @ocefpaf Just to be sure, what do I have to do to enable python3.7 and update to the latest pinnings?

Re-rendering will get you the latest pinning, but `py37` is still an ongoing operation. (Let me use my hacked conda-smithy here to force 3.7 for you.)

**Comment by ocefpaf** [comment]
@kmuehlbauer I'm preparing a PR but I have a question for you, can `wradlib` be noarch? I don't see any compiled extensions or `2to3` dependency.

**Comment by kmuehlbauer** [comment]
@ocefpaf wradlib itself has no compiled extensions whatsoever. But the dependencies (gdal etc.) have. What does noarch really mean?

**Comment by ocefpaf** [comment]
> What does noarch really mean?

Good question. It actually means "some arch." `wradlib` itself can be shipped as `noarch` and we should be OK with #35 as long as all the dependencies are available in all the platforms we try to install `wradlib`

**Comment by kmuehlbauer** [comment]
OK, so for 2.7, 3.5 and 3.6 it should just work. Need to check if everything for 3.7 is already available.

**Comment by ocefpaf** [comment]
> Need to check if everything for 3.7 is already available.

Yep. We may need to build some of those on `Python 3.7`.

**Pull request closed without merging**
