### PR TITLE
V0.11.0

### PR DESCRIPTION
**Pull request by kmuehlbauer**

### CODE REVIEW

**Comment by ocefpaf** [comment]
@kmuehlbauer I would wait for https://github.com/conda-forge/h5py-feedstock/pull/28 to get everything consistent with latest `hdf5 1.10.1`.

**Comment by kmuehlbauer** [comment]
@ocefpaf What do you suggest, closing and repopening, when https://github.com/conda-forge/h5py-feedstock/pull/28 is ready?

**Comment by ocefpaf** [comment]
> @ocefpaf What do you suggest, closing and repopening, when https://github.com/conda-forge/h5py-feedstock/pull/28 is ready?

Sure. Or we can just restart the CIs (but closing now and opening later can prevent accidental merges).

**Comment by kmuehlbauer** [comment]
@ocefpaf I closed this down now. What timeframe do you see for https://github.com/conda-forge/h5py-feedstock/pull/28. Because I'll need that package in the stack by end of next week latest.

**Comment by ocefpaf** [comment]
If I can make windows work we should get it today/early tomorrow. If not I have no idea b/c I pinged the devs and no one answered.

**Comment by kmuehlbauer** [comment]
@ocefpaf As https://github.com/conda-forge/h5py-feedstock/pull/28 is merged and and already build, can I safely assume this can be merged too? Or are there other dependencies waiting?

**Comment by ocefpaf** [comment]
I think h5py is the last one for you here. Just be sure to check wradlib's
build log for zlib 1.2.11 and hdf5 1.10.1 before merging.

**Comment by kmuehlbauer** [comment]
@ocefpaf Travis and Circle are OK, but the windows builds pick up hdf5 1.8.x and sometimes also an older zlib. :🤤

**Comment by kmuehlbauer** [comment]
@ocefpaf I think I'll merge anyway. We can deal with possible windows problems later.

**Comment by ocefpaf** [comment]
I'll check what is holding windows back. Probably some dependencies from
defaults.

**Pull request merged**
